#!/bin/sh
set -eu

VERSION="${1:?usage: tools/generate-homebrew-cask.sh <tag> <checksums.txt>}"
CHECKSUMS_FILE="${2:?usage: tools/generate-homebrew-cask.sh <tag> <checksums.txt>}"

version_no_v="${VERSION#v}"

checksum_for() {
	target="$1"
	awk -v file_name="$target" '$2 == file_name { print $1; exit }' "$CHECKSUMS_FILE"
}

darwin_amd64_asset="agentremote_v${version_no_v}_darwin_amd64.tar.gz"
darwin_arm64_asset="agentremote_v${version_no_v}_darwin_arm64.tar.gz"
linux_amd64_asset="agentremote_v${version_no_v}_linux_amd64.tar.gz"
linux_arm64_asset="agentremote_v${version_no_v}_linux_arm64.tar.gz"

darwin_amd64_sha="$(checksum_for "$darwin_amd64_asset")"
darwin_arm64_sha="$(checksum_for "$darwin_arm64_asset")"
linux_amd64_sha="$(checksum_for "$linux_amd64_asset")"
linux_arm64_sha="$(checksum_for "$linux_arm64_asset")"

for value in "$darwin_amd64_sha" "$darwin_arm64_sha" "$linux_amd64_sha" "$linux_arm64_sha"; do
	if [ -z "$value" ]; then
		printf '%s\n' "error: missing checksum entry in $CHECKSUMS_FILE" >&2
		exit 1
	fi
done

cat <<EOF
# This file is generated by tools/generate-homebrew-cask.sh. DO NOT EDIT.
cask "agentremote" do
  name "AgentRemote Manager"
  desc "AgentRemote Manager for Beeper"
  homepage "https://github.com/beeper/agentremote"
  version "${version_no_v}"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentremote"

  on_macos do
    on_intel do
      url "https://github.com/beeper/agentremote/releases/download/v#{version}/agentremote_v#{version}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64_sha}"
    end
    on_arm do
      url "https://github.com/beeper/agentremote/releases/download/v#{version}/agentremote_v#{version}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64_sha}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/beeper/agentremote/releases/download/v#{version}/agentremote_v#{version}_linux_amd64.tar.gz"
      sha256 "${linux_amd64_sha}"
    end
    on_arm do
      url "https://github.com/beeper/agentremote/releases/download/v#{version}/agentremote_v#{version}_linux_arm64.tar.gz"
      sha256 "${linux_arm64_sha}"
    end
  end

  # No zap stanza required
end
EOF
